if (self.CavalryLogger) { CavalryLogger.start_js(["RDPtp"]); }

__d("ProfileEditFlowAboutItemsStatusChanged",["CSS","DOMQuery","Event","tidyEvent"],(function(a,b,c,d,e,f){__p&&__p();a=function(){"use strict";__p&&__p();function a(a,c){__p&&__p();var d=this,e=this.$1(a);b("tidyEvent")(b("Event").listen(a,"click",function(f){__p&&__p();if(!b("DOMQuery").isNodeOfType(f.getTarget(),"input"))return;f=d.$1(a);var g=!1;for(var h in f)if(f[h]!==e[h]){g=!0;break}b("CSS").conditionShow(c,g)}))}var c=a.prototype;c.$1=function(a){var c={};b("DOMQuery").scry(a,"input").map(function(a){return c[a.id]=a.checked});return c};return a}();e.exports=a}),null);
__d("ProfileEditFlowModalEvents",[],(function(a,b,c,d,e,f){a=Object.freeze({PROFILE_CHANGED:"ProfileEditPublicModalEvents/profileChanged",PROFILE_PIC_UPLOADED:"ProfileEditPublicModalEvents/profilePicUploaded"});e.exports=a}),null);
__d("ProfileEditFlowModalManager",["Arbiter","ProfileEditFlowModalEvents","TimelineProfilePicConfig","tidyEvent"],(function(a,b,c,d,e,f){__p&&__p();a=function(){"use strict";__p&&__p();function a(){this.$1=!1,this.$2=!1}var c=a.prototype;c.informProfilePictureUploaded=function(a){b("Arbiter").inform(b("ProfileEditFlowModalEvents").PROFILE_PIC_UPLOADED,a)};c.isOpen=function(){return this.$1};c.hasProfileChanged=function(){return this.$2};c.setIsOpen=function(a){this.$1=a};c.subscribeProfileChanged=function(){var a=this;b("tidyEvent")(b("Arbiter").subscribeOnce(b("ProfileEditFlowModalEvents").PROFILE_CHANGED,function(){a.$2=!0}))};c.subscribeOnceProfilePictureUploaded=function(a){b("tidyEvent")([b("Arbiter").subscribeOnce(b("ProfileEditFlowModalEvents").PROFILE_PIC_UPLOADED,a),b("Arbiter").subscribeOnce(b("TimelineProfilePicConfig").success,a)])};return a}();e.exports=new a()}),null);
__d("ProfileEditFlowModalManagerInit",["ProfileEditFlowModalManager","ReloadPage","URI","destroyOnUnload","goURI"],(function(a,b,c,d,e,f){a={init:function(a,c){var d=a.subscribeOnce("hide",function(){b("ProfileEditFlowModalManager").isOpen()&&b("ProfileEditFlowModalManager").setIsOpen(!1),b("ProfileEditFlowModalManager").hasProfileChanged()&&(c!==null&&c!==""?b("goURI")(new(b("URI"))(c)):b("ReloadPage").now())});b("destroyOnUnload")(function(){return d.unsubscribe()});b("ProfileEditFlowModalManager").setIsOpen(!0);b("ProfileEditFlowModalManager").subscribeProfileChanged()}};e.exports=a}),null);
__d("ProfileEditFlowProfileChanged",["Arbiter","ProfileEditFlowModalEvents"],(function(a,b,c,d,e,f){a={profileChanged:function(){b("Arbiter").inform(b("ProfileEditFlowModalEvents").PROFILE_CHANGED)}};e.exports=a}),null);
__d("ProfileEditFlowSectionHeader.react",["cx","DOMContainer.react","Image.react","Layout.react","React","XUIGrayText.react","isNode"],(function(a,b,c,d,e,f,g){__p&&__p();var h=b("Layout.react").Column,i=b("Layout.react").FillColumn;a=function(a){"use strict";__p&&__p();babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.render=function(){var a=null;b("isNode")(this.props.buttonGroup)?a=b("React").createElement(b("DOMContainer.react"),null,this.props.buttonGroup):this.props.buttonGroup&&(a=this.props.buttonGroup);var c=null;(a||this.props.children)&&(c=b("React").createElement(h,null,this.props.children,a));return b("React").createElement(b("Layout.react"),{className:"_41mp _2pi8 _2pi4"},b("React").createElement(i,null,b("React").createElement(b("Image.react"),{className:"_41mq _3-90",src:this.props.glyph}),b("React").createElement(b("XUIGrayText.react"),{className:"_41mq _2pii",shade:"medium",size:"header4",weight:"bold"},this.props.text)),c)};return c}(b("React").Component);e.exports=a}),null);
__d("ProfileCustomExpirationStrings",["fbt","DateConsts"],(function(a,b,c,d,e,f,g){__p&&__p();a={BUTTON_SET:g._("Definir"),ERROR_NOTICE:g._("Selecione um hor\u00e1rio de t\u00e9rmino que esteja pelo menos 1 hora no futuro."),getExpirationString:function(a){if(a<b("DateConsts").SEC_PER_DAY)return this._getHourString(a);else if(a<b("DateConsts").SEC_PER_WEEK)return this._getDayString(a);else return this._getWeekString(a)},_getHourString:function(a){a=Math.round(a/b("DateConsts").SEC_PER_HOUR);return g._({"*":"{numHours} horas","_1":"1 hora"},[g._plural(a,"numHours")])},_getDayString:function(a){a=Math.round(a/b("DateConsts").SEC_PER_DAY);return g._({"*":"{numDays} dias","_1":"1 dia"},[g._plural(a,"numDays")])},_getWeekString:function(a){a=Math.round(a/b("DateConsts").SEC_PER_WEEK);return g._({"*":"{numWeeks} semanas","_1":"1 semana"},[g._plural(a,"numWeeks")])}};e.exports=a}),null);
__d("ProfileTemporaryOption",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({HOUR:3600,DAY:86400,WEEK:604800,PERMANENT:-1,CUSTOM:-2})}),null);